on:
  workflow_call:
  workflow_dispatch:

jobs:
  bvt-compatibility:
    name: ${{ matrix.compiler.family }}-${{ matrix.compiler.version }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {family: gcc, version: 13, modules: false, doc_tests: true}
          - {family: gcc, version: 14, modules: true, doc_tests: true}
          - {family: clang, version: 16, modules: false, doc_tests: false}
          - {family: clang, version: 17, modules: false, doc_tests: true}
          - {family: clang, version: 18, modules: false, doc_tests: true}
          - {family: clang, version: 19, modules: false, doc_tests: true}
          - {family: clang, version: 20, modules: true, doc_tests: true}
          - {family: clang, version: 21, modules: true, doc_tests: true}

    steps:
    - uses: actions/checkout@v6

    - name: Install gcc
      if: ${{ matrix.compiler.family == 'gcc' }}
      run: |
        sudo apt install -y 'g++-${{ matrix.compiler.version }}'
        cat <<'EOF' >> "$GITHUB_ENV"
        CC=gcc-${{ matrix.compiler.version }}
        CXX=g++-${{ matrix.compiler.version }}
        EOF

    - name: Install clang
      if: ${{ matrix.compiler.family == 'clang' }}
      run: |
        version='${{ matrix.compiler.version }}'
        if [ "$version" -ge 21 ]; then
          curl https://apt.llvm.org/llvm.sh | sudo bash -s -- "$version"
        fi
        sudo apt install -y "clang-$version" "clang-tools-$version" "libc++-$version-dev" "libc++abi-$version-dev"
        cat <<'EOF' >> "$GITHUB_ENV"
        CC=clang-${{ matrix.compiler.version }}
        CXX=clang++-${{ matrix.compiler.version }}
        CXXFLAGS=-stdlib=libc++
        EOF

    - name: Check toolchain versions
      run: |
        "$CXX" --version
        cmake --version
        ninja --version

    - name: Build and run test with cmake
      run: |
        cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release '-DPROXY_BUILD_MODULES=${{ matrix.compiler.modules }}' '-DBUILD_DOC_TESTING=${{ matrix.compiler.doc_tests }}'
        cmake --build build -j
        ctest --test-dir build -j
