name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - lkg

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r mkdocs/requirements.txt

      - name: Build site
        run: mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@v5
